---
title: "Montout"
author: "Mathieu Montout"
format: html
---

# 1 intro

```{r}
#loading of the packages
library(ggplot2)
library(here)
library(dplyr)
library(tidyr)
library(vroom)
```

## 1.1 Study organisation

## 1.2 Data set

### Q1

```{r}
here::i_am("grades-test_lab2.Rproj")
grades <- vroom(here("grades.csv"))
```

# 2 Simple analyses

### Q2

```{r}
num = nrow(grades)
cat(sprintf("The data set contains %d grades.",num))

```

### Q3

```{r}
 num_stud_data <-grades|>
  distinct(id)|>
  nrow()
cat(sprintf("The data set contains %d grades.",num_stud_data))
```

```{r}

num_stu = grades|>
  distinct(id)|>
  summarise(
    n()
  )
cat(sprintf("The data set contains %d grades.", as.character(num_stu)))
```

### Q4

```{r}
students <- grades|>
  distinct(id, .keep_all = TRUE)|>
  select(id,group,grade)
students|>
  slice(1:10)
```

### Q5

```{r}
students_2 <- students|>
  group_by(group)|>
  summarise(
    num = n()
  )

  
```

```{r}
ggplot(students_2, aes(x=group, y=num, fill=group))+
         geom_line()+
  labs(title = "Number of Students per Group",
       x = "Group",
       y = "Number of Students") +
  theme_minimal() +
  theme(legend.position = "none")
```

### Q6

```{r}
avg_group<-grades|>
  filter(course=="Electrical Engineering and Telegraphy")|>
  group_by(group)|>
  summarise(
    mean = mean(grade)
  )
```

```{r}
ggplot(avg_group, aes(group, mean))+
         geom_col()
```

### Q7

```{r}

```

##Exo 3

### Q8

```{r}
grades|>
  group_by(id,group)|>
  summarise(n(), .groups = 'drop')|>
  slice(1:10)
```

```{r}
grades|>
  group_by(id,group)|>
  summarise(t = n(), .groups = 'drop')|>
  summarise(min(t),, max(t),mean(t), median(t))


```

### Q9

```{r}
grades_fashion <- grades|>
  filter(course=="Fashion Design and Textile Innovation")|>
  group_by(id,group)|>
  summarise(grade = n(), .groups = 'drop')

grades_fashion|>
  slice(1:10)
```


### Q10

```{r}
grades_fashion_graph<-grades_fashion|>
  group_by(grade)|>
  summarise(num_student = n())
```


```{r}
ggplot(grades_fashion_graph,aes(grade,num_student))+
  geom_col()
```


